### ISSUE TITLE
Exception when latitude or longitude is 0

### ISSUE THREAD

**Issue by vladim1** [2amigos/yii2-leaflet-library#17]
I want to create a marker in Great Britain. The coordinates are:
```php
... new LatLng(['lat' => 51.5371, 'lng' => 0])
```
But I can't create it, because I catch an exception:
```php
'lat' and 'lng' attributes cannot be empty.

in /var/www/project/vendor/2amigos/yii2-leaflet-extension/types/LatLng.php
at line 52
```
It looks like empty function should be replaced with another condition, because zero is percieved as empty value
```php
if (empty($this->lat) || empty($this->lng)) {
```

**Comment by tonydspaniard** [comment]
Good catch @vladim1 should be tested against `null` instead. We are currently refactoring the libraries. Will fix it when is time for `yii2-leaftlet-library`

**Comment by tonydspaniard** [comment]
@vladim1 please see #18 and https://github.com/2amigos/yii2-leaflet-extension 

The latest is going to be the repo from now on... once all is moved, this repository will be removed.

**Comment by tonydspaniard** [comment]
@vladim1 done on https://github.com/2amigos/yii2-leaflet-extension/blob/master/src/types/LatLng.php#L51 

This repo is going to be closed
