### ISSUE TITLE
Extend lib

### ISSUE THREAD

**Issue by MUTOgen** [2amigos/yii2-leaflet-library#7]
Hi, thanks for great component.
Is there any way to add new Leaflet plugins here and extend functionality of your component?
Could you provide us an information about that?

There are many plugins here http://leafletjs.com/plugins.html#notable-leaflet-plugins , some of that plugins very nice.

**Comment by tonydspaniard** [comment]
Currently I have done the ones in the repository so far (on our next release will publish leafLetDrawPlugin which allows you to have editable maps. 

Check the  Abstract class Plugin (https://github.com/2amigos/yii2-leaflet-library/blob/master/Plugin.php) and how we implemented some of the plugins. Any additions to the library are more than welcome!
