### ISSUE TITLE
The latest commit is not published

### ISSUE THREAD

**Issue by arjenmeijer** [2amigos/yii2-leaflet-library#8]
After an update with composer the 1.2 version from april is loaded without the commit of september. Please publish a new version with all the latest commits.

**Comment by tarleb** [comment]
You probably know this, but it seems worth mentioning: The newest version (i.e. the current master) can be loaded by setting the libraries version to `dev-master`:

```
    "require": {
        "2amigos/yii2-leaflet-extension": "dev-master",
    }
```

I second the call for a new release.  I hope to get some patches ready till then.

**Comment by tonydspaniard** [comment]
I am sooo busy! I try to do it asap

**Comment by tarleb** [comment]
Don't sweat it.  I'm very glad that this library exists at all, thanks a lot for this!  It makes using LeafLet incredibly simple.

**Comment by tonydspaniard** [comment]
Done! both the split merge branch and this repository:

- https://github.com/2amigos/yii2-leaflet-library/tree/0.1.3 
- https://github.com/2amigos/yii2-leaflet-extension/tree/0.1.3 

Thanks for your patience guys

**Comment by tarleb** [comment]
Awesome, thanks :smiley:
