### ISSUE TITLE
Why test if map exists?

### ISSUE THREAD

**Issue by arjenmeijer** [2amigos/yii2-leaflet-library#9]
The test in vendor/2amigos/yii2-leaflet-extension/layers on line 70 prevents the map from being shown.
Only by adding an extra ".addTo(map)") the map will show.

		$js = "L.tileLayer('$this->urlTemplate', $options)" . ($map !== null ? ".addTo($map);" : ".addTo(map)");

What is the use of this test? It should throw an error and not skip the addTo part!

**Comment by tonydspaniard** [comment]
There are two ways to create a tileLayer, one create an independent object and then append it on the JS, and the other is to create the object and use its addTo method if you have set the client variable name in its `$map` attribute. 

Thats why if `$map` is not set, it just returns the js to create the object, nothing else.

**Comment by arjenmeijer** [comment]
Thanks for the response, but I do not get. I upgraded to the dev version and now the code below does not work due to a missing variable name in the javscript of the rendered view:
<script type="text/javascript">jQuery(document).ready(function () {
function _init(){
var ???????name is missing????  = L.map('w0', {"center":[52.1828,5.93],"zoom":16});

What I am do wrong?

Controller:
    public function actionLocatie()    { // http://www.yiiframework.com/extension/yii2-leaflet-library/
        return $this->render('locatie', [
            'dataProvider' => new ActiveDataProvider([
                    'query' => Dagboek::find(),
                    'pagination' => false
                ])
        ]);

View locatie.php:

<?php
use dosamigos\leaflet\types\LatLng;
use dosamigos\leaflet\layers\Marker;
use dosamigos\leaflet\layers\TileLayer;
use dosamigos\leaflet\LeafLet;
use dosamigos\leaflet\widgets\Map;
use yii\widgets\ListView
 ?>
...
// first lets setup the center of our map
$center = new LatLng(['lat' => 52.1828, 'lng' => 5.93]);
 
// now lets create a marker that we are going to place on our map
// $marker = new Marker(['latLng' => $center, 'popupContent' => 'Uchelen']);
 
// The Tile Layer (very important) // http://otile3.mqcdn.com/tiles/1.0.0/map/1/0/0.jpeg'
$tileLayer = new TileLayer([
    'urlTemplate' => 'http://otile{s}.mqcdn.com/tiles/1.0.0/map/{z}/{x}/{y}.jpeg',
   'clientOptions' => [
        'attribution' => 'Tiles Courtesy of <a href="http://www.mapquest.com/">MapQuest</a> '
	+'&mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
        'subdomains' => '1234'
    ]
]);
 
// now our component and we are going to configure it
$leaflet = new LeafLet([
    'tileLayer' => $tileLayer, // set the TileLayer
    'center' => $center, // set the center
    'zoom'=> 16  // hoe ver inzoomen
]);
// add the markers (addLayer is used to add different layers to our map)
    foreach($dataProvider->getModels() as $record) {
   	// generate markers
	// New LatLng verplichte class
	$positie = new LatLng(['lat' => $record->Latitude, 'lng' => $record->Longitude]);
    	$marker = new Marker([
        	'latLng' => $positie,
        	'popupContent' => "<h4>".$record->gebeurtenis->samenvatting."</h4><h5>".$record->tijdstip."</h5>".$record->gebeurtenis->tekst,
    		]);
	$leaflet->addLayer($marker);
    }
 
// finally render the widget
echo Map::widget(['leafLet' => $leaflet]);

**Comment by tarleb** [comment]
@arjenmeijer: I think you forgot to post the code snippet which is causing you trouble.

**Comment by tonydspaniard** [comment]
@arjenmeijer  are you using the tileLayer? if so, have you set its map name? I need to update that and put a default name to it.

**Comment by arjenmeijer** [comment]
@tonydspaniard Do you have an example of setting the map name?

**Comment by tarleb** [comment]
@tonydspaniard: The `map` issue irked me a bit, too, so I started to refactor some code.  I didn't get to the true issue yet, plus I'm pretty sure that [I'm overdoing it](https://github.com/tarleb/yii2-leaflet-library/tree/refactoring).  In case you think the refactoring approach is a terrible idea, now would be a very good time to stop me.  If you think it's ok, let me know, and I should have a PR for you by this time tomorrow.

**Comment by tonydspaniard** [comment]
@tarleb yeah is true that the 'map' issue is a problem. We need to rethink this approach of forcing the 'tileLayer' to have a 'map' id and throw an exception if failed. As you can see it descents from `Layer` class and this class allows the use of 'empty' values. 

The way to solve this issue is to update this function: https://github.com/2amigos/yii2-leaflet-library/blob/master/LeafLet.php#L134 with the following: 

```php 
        public function setTileLayer(TileLayer $tileLayer)
	{
		if (!empty($tileLayer->map) && strcmp($tileLayer->map, $this->name) !== 0) {
			$this->name = $tileLayer->map;
		} 
                // WE SHOULD ADD THIS
                if(empty($tileLayer->map)) {
                       $tileLayer->map = $this->name;
                }
		$this->_tileLayer = $tileLayer;
		return $this;
	}

```
I believe this is the problem, that we do not check for the 'map' attribute of the tileLayer and due to that the following code:
https://github.com/2amigos/yii2-leaflet-library/blob/master/widgets/Map.php#L95 renders the wrong javascript trying to initialize the tileLayer with empty variable map name.

I have checked your code a little bit. Is good to review the API structure and how it was done. Maybe is better to use interfaces instead of abstract classes I am not sure. And why I would stop your creativity? :)

**Comment by tonydspaniard** [comment]
@tarleb nevertheless, make sure the refactoring doesn't have any B/C issues.

**Comment by tonydspaniard** [comment]
@arjenmeijer show me your code

**Comment by arjenmeijer** [comment]
@tonydspaniard  with the change the map is working well. Thank you!  My code was cut off, sorry. Just the standard example.

I recomment to change the example with:
echo Map::widget(['leafLet' => $leaflet,'height' => '600']);
for a map of 600px height as the height is an important setting. For new users like me it is not obvious were to find this information.

**Comment by tonydspaniard** [comment]
@arjenmeijer I will do... I will also do the change to fix that lag on TileLayer
